version: '3'

services:
  app:
    build:
      context: .
    ports:
    - "8000:8000"
    volumes:
    - ./app:/app
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate && 
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
     - ./.env.dev
    depends_on:
     - pgdb
  
  pgdb:
    image: postgres:16-alpine
    env_file:
     - ./.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
     - "5433:5433"

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env.dev
    ports:
      - "5050:80"

volumes:
  pgdata:
